#!/bin/sh -
### BEGIN INIT INFO
# Provides: bluetooth-agent
# Required-Start: $local_fs $syslog bluetooth pulseaudio
# Required-Stop: $local_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Makes Bluetooth discoverable and connectable
### END INIT INFO

#! /bin/sh

# /etc/init.d/bluetooth-agent
USER=root
HOME=/root
export USER HOME
case "$1" in
    start)
        log_daemon_msg "setting bluetooth discoverable"
        sleep 1
        sudo hciconfig hci0 piscan
        start-stop-daemon -S -x /usr/local/bin/simple-agent.autotrust &
        log_daemon_msg "bluetooth-agent started"
        log_end_msg 0
        ;;
    stop)
        log_daemon_msg "Stopping bluetooth-agent"
        start-stop-daemon -K -x /usr/local/bin/simple-agent.autotrust
        log_daemon_msg "bluetooth-agent stopped"
        log_end_msg 0
        ;;
    restart)
        log_daemon_msg "Restarting bluetooth-agent"
        start-stop-daemon -K -x /usr/local/bin/simple-agent.autotrust
        start-stop-daemon -S -x /usr/local/bin/simple-agent.autotrust &
        log_daemon_msg "bluetooth-agent restarted"
        log_end_msg 0
        ;;
    *)
        log_daemon_msg "Usage: /etc/init.d/bluetooth-agent {start|stop}"
        exit 1
        ;;
esac
exit 0
